const categories = [
  {
    id: 3,
    name: "Cookies",
  },
  {
    id: 1,
    name: "Mexican Food",
  },
  {
    id: 2,
    name: "Italian Food",
  },
  {
    id: 4,
    name: "Smoothies",
  },
  {
    id: 0,
    name: "Pizza",
  },
];

const recipes = [
  {
    recipeId: 122,
    categoryId: 3,
    title: "Oatmeal Cookies",
    time: "15",
    ingredients: [
      [0, "200ml"],
      [1, "5g"],
      [2, "300g"],
    ],
    description:
      "-- Start with cleaned and peeled russet potatoes that you have cut into 3/8-inch match sticks. Place in bowl of very cold water: keep rinsing and changing the water until the water is clear; drain thoroughly and dry with paper towels or a clean lint-free kitchen towel.\n\n -- Meanwhile, you preheat your hot oil to 350 degrees F. Place prepared taters in oil and cook about 5 minutes. They will have that blond-tone color to them. \n\n -- Note: Once you add cold potatoes to the hot oil, the temperature of your oil is going to drop - you want it to be somewhere between 330 - 325 degrees F. \n\n -- Remove from oil; drain and cool. Now - either refrigerate until ready to finish cooking, or cool completely and freeze up to 3 months. To freeze properly - place completely cooled fries in single layer on tray and place in freezer until frozen. Then bag them.\n\n -- To finish cooking - preheat your oil to 400* F. Add your cold fries (which will drop the oil temp - which is fine because you want it near the 375 degrees F. temp) and cook a few minutes until done. Lightly salt them and shake well so that the salt distributes well and they are not salty.",
  },
  {
    recipeId: 3,
    categoryId: 4,
    title: "Triple Berry Smoothie",
    time: "10",
    ingredients: [
      [59, "1"],
      [60, "1/2 lbs"],
      [61, "1/2 liters"],
    ],
    description:
      "In a blender, combine all ingredients and blend until smooth. Then divide between 2 cups and top with blackberries, if desired.",
  },
  {
    recipeId: 2,
    categoryId: 3,
    title: "Vegan Cookies",
    time: "30",
    ingredients: [
      [0, "2 quarts"],
      [16, "1"],
      [12, "1 cup"],
      [18, "1 cup"],
      [19, "1 teaspoon"],
      [1, "2 teaspoons"],
      [4, "1/4 teaspoons"],
      [7, "1/8 teaspoons"],
      [20, "1/2 teaspoons"],
      [21, "4"],
    ],
    description:
      "-- Beat the egg and then combine it with water in a bowl. Stir. Combine the flour, salt, MSG, pepper, onion powder and garlic powder in a gallon size zip lock bag. Pound each of the breast filets until about 1/4-inch thick. Then cut into bite sized pieces. Coat each piece with the flour mixture by shaking in the zip lock bag. Remove and coat in the egg mixture. Then coat in the flour mixture again. Shake to coat. Deep fry at 375 degrees for 10-12 minutes, until browned and crispy.",
  },
  {
    recipeId: 3,
    categoryId: 3,
    title: "Pumpkin Spice Cookies",
    time: "45",
    ingredients: [
      [0, "2 tablespoons"],
      [22, "1/2"],
      [23, "2 tablespoons"],
      [7, "2 cloves"],
      [3, "1 teaspoon"],
      [24, "1 tablespoon"],
      [25, "1 lb"],
      [1, "2 teaspoons"],
      [4, "2 teaspoons"],
      [26, "15 oz"],
      [27, "8"],
      [28, "2"],
      [29, "1 cup"],
    ],
    description:
      "-- In a medium pot over medium heat, heat 1 tablespoon oil. Add onion and cook until soft, 5 minutes. Add garlic and cook until fragrant, 1 minute more. Add tomato paste and stir to coat onion and garlic. Add ground beef and cook, breaking up meat with a wooden spoon, until no longer pink, 6 minutes. Drain fat.\n\n -- Return beef to pot and season with chili powder, paprika, salt, and pepper. Add tomato sauce and kidney beans. Bring to a boil, then reduce heat and let simmer 15 minutes. Add some chili to center of each tortilla, leaving room to fold in edges. Top with Fritos, then cheddar. Fold edges of tortillas toward the center, creating pleats. Invert Crunchwraps so pleats are on the bottom and stay together.\n\n -- In medium skillet over medium heat, heat remaining tablespoon oil. Add a Crunchwrap seam side down and cook until tortilla is golden, 3 to 5 minutes per side. Repeat with remaining Crunchwraps",
  },
  {
    recipeId: 1,
    categoryId: 3,
    title: "Brownies",
    time: "30",
    ingredients: [
      [1, "2 tablespoons"],
      [3, "1 tablespoon"],
      [4, "1 teaspoon"],
      [5, "1/2 teaspoons"],
      [6, "1/2 teaspoons"],
      [7, "1/2 teaspoons"],
      [8, "1/2 teaspoons"],
      [9, "1/2 teaspoons"],
      [10, "1/2 teaspoons"],
      [11, "1/2 teaspoons"],
      [12, "1/2 cups"],
      [13, "1 tablespoon"],
      [14, "1 tablespoon"],
      [15, "2 breasts, 2 thighs, 2 drumsticks, 2 wings"],
      [16, "1"],
      [17, "2 quarts"],
    ],
    description:
      "-- Preheat fryer to 350°F. Thoroughly mix together all spices. Combine spices with flour, brown sugar and salt. Dip chicken pieces in egg white to lightly coat them, then transfer to flour mixture. Turn a few times and make sure the flour mix is really stuck to the chicken.\n\n -- Repeat with all the chicken pieces. Let chicken pieces rest for 5 minutes so crust has a chance to dry a bit. Fry chicken in batches. Breasts and wings should take 12-14 minutes, and legs and thighs will need a few more minutes. Chicken pieces are done when a meat thermometer inserted into the thickest part reads 165°F. Let chicken drain on a few paper towels when it comes out of the fryer. Serve hot.",
  },
  {
    recipeId: 4,
    categoryId: 1,
    title: "Perfect Fish Tacos",
    time: "35",
    ingredients: [
      [30, "jucie of 1 "],
      [24, "2 teaspoons"],
      [0, "3 tablespoons"],
      [3, "1 teaspoon"],
      [31, "1/2 teaspoons"],
      [32, "1/2 teaspoons"],
      [4, "2 teaspoons"],
      [33, "1/2 lb"],
      [27, "8"],
      [14, "2 teasponns"],
      [34, "1"],
    ],
    description:
      "-- In a medium shallow bowl, whisk together olive oil, lime juice, paprika, chili powder, cumin, and cayenne. Add cod, tossing until evenly coated. Let marinate 15 minutes. Meanwhile, make slaw: In a large bowl, whisk together mayonnaise, lime juice, cilantro, and honey. Stir in cabbage, corn, and jalapeño. Season with salt and pepper.\n\n -- In a large nonstick skillet over medium-high heat, heat vegetable oil. Remove cod from marinade and season both sides of each filet with salt and pepper. Add fish flesh side-down. Cook until opaque and cooked through, 3 to 5 minutes per side.\n\n -- Let rest 5 minutes before flaking with a fork. Assemble tacos: Serve fish over grilled tortillas with corn slaw and avocado. Squeeze lime juice on top and garnish with sour cream. ",
  },
  {
    recipeId: 5,
    categoryId: 1,
    title: "Chicken Fajitas",
    time: 35,
    ingredients: [
      [9, "1/2 teaspoons"],
      [0, "4 tablespoons"],
      [1, "1/2 teaspoons"],
      [30, "2 tablespoons"],
      [31, "1 teaspoon"],
      [7, "1 teaspoon"],
      [24, "1/2 teaspoons"],
      [3, "1/2 teaspoons"],
      [21, "1 pound"],
      [22, "1/2 cup"],
      [27, "6"],
      [36, "4"],
      [37, "1/2"],
      [38, "1/2"],
    ],
    description:
      "-- In a large bowl, combine 2 tablespoons oil, lemon juice and seasonings; add the chicken. Turn to coat; cover. Refrigerate for 1-4 hours In a large skillet, saute peppers and onions in remaining oil until crisp-tender. Remove and keep warm. Drain chicken, discarding marinade. In the same skillet, cook chicken over medium-high heat for 5-6 minutes or until no longer pink.\n\n -- Return pepper mixture to pan; heat through. Spoon filling down the center of tortillas; fold in half. Serve with toppings as desired.",
  },
  {
    recipeId: 6,
    categoryId: 2,
    title: "Buffalo Pizza",
    time: 50,
    ingredients: [
      [39, "1 lb"],
      [40, "1 cup"],
      [41, "1/2 cup"],
      [42, "1/4 cup"],
      [43, "2 tablespoons"],
      [44, "1/2 cup"],
      [7, "1/4 teaspoons"],
      [5, "1/4 teaspoons"],
      [30, "1/4 teaspoons"],
      [45, "2 oz"],
      [12, "for dusting"],
      [4, "1/2 teaspoons"],
      [47, "2"],
      [46, "9 oz"],
    ],
    description:
      "-- Place a rack in upper third of oven. Place a large cast-iron skillet on rack and preheat oven to 500° (or as high as your oven will go). Place pizza dough in a large bowl, pour a little oil over, and turn to coat. Cover bowl with plastic and let dough proof at room temperature while pan and oven heat up.\n\n -- Meanwhile, cook hot sauce, marinara sauce, and butter in a medium saucepan over medium heat, stirring occasionally, until butter is melted. Stir in cream, reduce heat to low, and simmer, stirring occasionally, until slightly thickened and warmed through, about 10 minutes. Heat 1 Tbsp. oil in a large skillet over medium-high. Add chicken, toss to coat, then add ¼ cup Buffalo sauce.\n\n -- Cook chicken, tossing occasionally, until heated through, about 2 minutes. Reduce heat and simmer, stirring often, until chicken is well coated and sauce is slightly thickened, about 5 minutes. Meanwhile, whisk yogurt, lemon juice, celery salt, garlic powder, ¼ cup blue cheese, ½ tsp. pepper, and 2 Tbsp. water in a small bowl, adding more water if sauce seems too thick (it should be pourable); set aside.\n\n -- Turn out dough onto a lightly floured work surface. Shape with your hands into a round that’s slightly larger than the cast-iron skillet you’re using. Take hot skillet out of oven (watch that handle!) and place on a heatproof surface. Add a little flour to pan. Lay dough in skillet, then work edges of dough up sides of skillet with your fingertips (use a rubber spatula or wooden spoon if you’re nervous about touching the hot pan). Drizzle a little oil around inside edge of pan so that it trickles behind and underneath dough, which will encourage browning and help it release.\n\n -- Spread about ⅓ cup Buffalo sauce over dough. Arrange mozzarella over, then top with remaining ¼ cup blue cheese. Arrange chicken mixture on top. Bake pizza on top rack until crust and cheese are nicely browned, 15–20 minutes. Transfer skillet to stovetop (again, watch that handle!) and let pizza rest a few minutes. Using a spatula, slide pizza onto a cutting board or platter. Arrange celery over, then top with reserved blue cheese dressing. Season with pepper, then drizzle with oil.",
  },
  {
    recipeId: 0,
    categoryId: 0,
    title: "Classic Lasagna",
    time: "15",
    ingredients: [
      [0, "200ml"],
      [1, "5g"],
      [2, "300g"],
    ],
    description:
      "-- Start with cleaned and peeled russet potatoes that you have cut into 3/8-inch match sticks. Place in bowl of very cold water: keep rinsing and changing the water until the water is clear; drain thoroughly and dry with paper towels or a clean lint-free kitchen towel.\n\n -- Meanwhile, you preheat your hot oil to 350 degrees F. Place prepared taters in oil and cook about 5 minutes. They will have that blond-tone color to them. \n\n -- Note: Once you add cold potatoes to the hot oil, the temperature of your oil is going to drop - you want it to be somewhere between 330 - 325 degrees F. \n\n -- Remove from oil; drain and cool. Now - either refrigerate until ready to finish cooking, or cool completely and freeze up to 3 months. To freeze properly - place completely cooled fries in single layer on tray and place in freezer until frozen. Then bag them.\n\n -- To finish cooking - preheat your oil to 400* F. Add your cold fries (which will drop the oil temp - which is fine because you want it near the 375 degrees F. temp) and cook a few minutes until done. Lightly salt them and shake well so that the salt distributes well and they are not salty.",
  },
  {
    recipeId: 7,
    categoryId: 2,
    title: "Spaghetti Carbonara",
    time: 15,
    ingredients: [
      [48, "50g"],
      [49, "100g"],
      [50, "350g"],
      [51, "2 plump"],
      [42, "50g"],
      [16, "3"],
      [1, "2 teaspoons"],
      [4, "2 teaspoons"],
    ],
    description:
      "-- Put the egg yolks into a bowl, finely grate in the Parmesan, season with pepper, then mix well with a fork and put to one side. Cut any hard skin off the pancetta and set aside, then chop the meat. Cook the spaghetti in a large pan of boiling salted water until al dente.\n\n -- Meanwhile, rub the pancetta skin, if you have any, all over the base of a medium frying pan (this will add fantastic flavour, or use 1 tablespoon of oil instead), then place over a medium-high heat. Peel the garlic, then crush with the palm of your hand, add it to the pan and leave it to flavour the fat for 1 minute. Stir in the pancetta, then cook for 4 minutes, or until it starts to crisp up. Pick out and discard the garlic from the pan, then, reserving some of the cooking water, drain and add the spaghetti.\n\n -- Toss well over the heat so it really soaks up all that lovely flavour, then remove the pan from the heat. Add a splash of the cooking water and toss well, season with pepper, then pour in the egg mixture – the pan will help to cook the egg gently, rather than scrambling it. Toss well, adding more cooking water until it’s lovely and glossy. Serve with a grating of Parmesan and an extra twist of pepper.",
  },
  {
    recipeId: 8,
    categoryId: 2,
    title: "Lazania",
    time: 60,
    ingredients: [
      [36, "1 large"],
      [25, "1 pound"],
      [51, "5 cloves"],
      [52, "1 pound"],
      [53, "1 pound"],
      [54, "1 28 ounce can"],
      [23, "2 6 ounce can"],
      [55, "2 tablespoons"],
      [56, "1/4 cup"],
      [10, "1/2 cup"],
      [1, "1/2 teaspoons"],
      [58, "1 teaspoon"],
      [4, "1/4 teaspoons"],
      [16, "1 large"],
      [46, "1 pound"],
      [48, "1 cup"],
      [57, "30 ounces"],
    ],
    description:
      "-- Cook noodles according to package directions; drain. Meanwhile, in a Dutch oven, cook sausage, beef and onion over medium heat 8-10 minutes or until meat is no longer pink, breaking up meat into crumbles. Add garlic; cook 1 minute. Drain. Stir in tomatoes, tomato paste, water, sugar, 3 tablespoons parsley, basil, fennel, 1/2 teaspoon salt and pepper; bring to a boil. Reduce heat; simmer, uncovered, 30 minutes, stirring occasionally. In a small bowl, mix egg, ricotta cheese, and remaining parsley and salt. Preheat oven to 375°. Spread 2 cups meat sauce into an ungreased 13x9-in. baking dish. Layer with 3 noodles and a third of the ricotta mixture. Sprinkle with 1 cup mozzarella cheese and 2 tablespoons Parmesan cheese.\n\n -- Repeat layers twice. Top with remaining meat sauce and cheeses (dish will be full). Bake, covered, 25 minutes. Bake, uncovered, 25 minutes longer or until bubbly. Let stand 15 minutes before serving.",
  },
];

const ingredients = [
  {
    ingredientId: 0,
    name: "Oil",
    quantity: "200 mL",
  },
  {
    ingredientId: 1,
    name: "Salt",
    quantity: "5 g",
  },
  {
    ingredientId: 2,
    name: "Russet potatoes",
    quantity: "300 g",
  },
  {
    ingredientId: 3,
    name: "Paprika",
    quantity: "1 pinch",
  },
  {
    ingredientId: 4,
    name: "Black Pepper",
    quantity: "1 pinch",
  },
  {
    ingredientId: 5,
    name: "Celery salt",
  },
  {
    ingredientId: 6,
    name: "Dried sage",
    quantity: "500 g",
  },
  {
    ingredientId: 7,
    name: "Garlic powder",
    quantity: "500 g",
  },
  {
    ingredientId: 8,
    name: "Ground allspice",
    quantity: "500 g",
  },
  {
    ingredientId: 9,
    name: "Dried oregano",
    quantity: "500 g",
  },
  {
    ingredientId: 10,
    name: "Dried basil",
    quantity: "500 g",
  },
  {
    ingredientId: 11,
    name: "Dried marjoram",
    quantity: "500 g",
  },
  {
    ingredientId: 12,
    name: "All-purpose flour",
    quantity: "500 g",
  },
  {
    ingredientId: 13,
    name: "Brown sugar",
    quantity: "500 g",
  },
  {
    ingredientId: 14,
    name: "Kosher salt",
    quantity: "500 g",
  },
  {
    ingredientId: 15,
    name: "Whole chicken",
    quantity: "500 g",
  },
  {
    ingredientId: 16,
    name: "Eggs",
    quantity: "500 g",
  },
  {
    ingredientId: 17,
    name: "Quarts neutral oil",
    quantity: "500 mL",
  },
  {
    ingredientId: 18,
    name: "Water",
    quantity: "500 mL",
  },
  {
    ingredientId: 19,
    name: "Onion Powder",
    quantity: "500 g",
  },
  {
    ingredientId: 20,
    name: "MSG",
    quantity: "500 g",
  },
  {
    ingredientId: 21,
    name: "Chicken Breast",
    quantity: "500 g",
  },
  {
    ingredientId: 22,
    name: "Onion chopped",
    quantity: "500 g",
  },
  {
    ingredientId: 23,
    name: "Tomato paste",
    quantity: "500 mL",
  },
  {
    ingredientId: 24,
    name: "Chilli Powder",
    quantity: "500 g",
  },
  {
    ingredientId: 25,
    name: "Ground Beef",
    quantity: "500 g",
  },
  {
    ingredientId: 26,
    name: "Can kidney beans, rinsed and drained ",
    quantity: "500 g",
  },
  {
    ingredientId: 27,
    name: "Large Tortillas",
    quantity: "500 g",
  },
  {
    ingredientId: 28,
    name: "Firtos",
    quantity: "500 g",
  },
  {
    ingredientId: 29,
    name: "Shredded cheddar",
    quantity: "500 g",
  },
  {
    ingredientId: 30,
    name: "Lime",
    quantity: "500 g",
  },

  {
    ingredientId: 31,
    name: "Ground cumin",
    quantity: "500 g",
  },
  {
    ingredientId: 32,
    name: "Cayenne pepper",
    quantity: "500 g",
  },
  {
    ingredientId: 33,
    name: "Flaky white fish",
    quantity: "500 g",
  },
  {
    ingredientId: 34,
    name: "Avocado",
    quantity: "500 g",
  },
  {
    ingredientId: 35,
    name: "Red Pepper Flakes",
    quantity: "500 g",
  },
  {
    ingredientId: 36,
    name: "Onions",
    quantity: "500 g",
  },
  {
    ingredientId: 37,
    name: "Green Pepper",
    quantity: "500 g",
  },
  {
    ingredientId: 38,
    name: "Red Pepper",
    quantity: "500 g",
  },
  {
    ingredientId: 39,
    name: "Pizza dough",
    quantity: "500 g",
  },
  {
    ingredientId: 40,
    name: "Ketchup sauce",
    quantity: "500 g",
  },
  {
    ingredientId: 41,
    name: "Hot Sauce",
    quantity: "500 g",
  },
  {
    ingredientId: 42,
    name: "Butter",
    quantity: "500 g",
  },
  {
    ingredientId: 43,
    name: "Heavy Cream",
    quantity: "500 g",
  },
  {
    ingredientId: 44,
    name: "whole-milk plain yogurt",
    quantity: "500 g",
  },
  {
    ingredientId: 45,
    name: "Cheese",
    quantity: "500 g",
  },
  {
    ingredientId: 46,
    name: "Mozzarella",
    quantity: "500 g",
  },
  {
    ingredientId: 47,
    name: "celery stalks",
    quantity: "500 g",
  },
  {
    ingredientId: 48,
    name: "Parmesan Chesse",
    quantity: "500 g",
  },
  {
    ingredientId: 49,
    name: "pancetta",
    quantity: "500 g",
  },
  {
    ingredientId: 50,
    name: "Spaghetti",
    quantity: "500 g",
  },
  {
    ingredientId: 51,
    name: "Garlic",
    quantity: "500 g",
  },
  {
    ingredientId: 52,
    name: "Lasagna noodles",
    quantity: "500 g",
  },
  {
    ingredientId: 53,
    name: "Italian sauce",
    quantity: "500 g",
  },
  {
    ingredientId: 54,
    name: "Crushed Tomatoes",
    quantity: "500 g",
  },
  {
    ingredientId: 55,
    name: "Sugar",
    quantity: "500 g",
  },
  {
    ingredientId: 56,
    name: "minced fresh parsley",
    quantity: "500 g",
  },
  {
    ingredientId: 57,
    name: "ricotta cheese",
    quantity: "500 g",
  },
  {
    ingredientId: 58,
    name: " fennel seed",
    quantity: "500 g",
  },
  {
    ingredientId: 59,
    name: "Banana",
    quantity: "500 g",
  },
  {
    ingredientId: 60,
    name: "Frozen Straberries",
    quantity: "500 g",
  },
  {
    ingredientId: 61,
    name: "Greek Yogurt",
    quantity: "500 g",
  },
];

module.exports = { categories, recipes, ingredients };
